import './shared/navbar';
import './pages/welcome';
import './pages/art-gallery';
import './pages/reservasi';
import './pages/caferesto';
import './pages/reservasi';
import './pages/kamidaur';
import './pages/legapetcare';
import './pages/halamanvenue';